multimedia: Refine video drivers recipes to fix eCRM build error
eCRM build error:
msm_vidc_driver.c:28:10: fatal error: 'vidc_hw_virt.h' file not found

Change-Id: I359e8e3a96a068abfcd159315de5609540c32ce5
Signed-off-by: Ferry Zhou <tianguiz@qti.qualcomm.com>
(cherry picked from commit 7685f063b7d6b6286164400dd881c4ff6c56e8d1)